const data = [
  {
    ID: 1,
    Name: "John Smith",
    Age: 25,
    Occupation: "Engineer",
    "Father's ID": 8,
  },
  {
    ID: 2,
    Name: "Sarah Johnson",
    Age: 32,
    Occupation: "Teacher",
    "Father's ID": 14,
  },
  {
    ID: 3,
    Name: "Michael Brown",
    Age: 41,
    Occupation: "Doctor",
    "Father's ID": 2,
  },
  {
    ID: 4,
    Name: "Emily Davis",
    Age: 28,
    Occupation: "Lawyer",
    "Father's ID": 10,
  },
  {
    ID: 5,
    Name: "David Wilson",
    Age: 35,
    Occupation: "Architect",
    "Father's ID": 9,
  },
  {
    ID: 6,
    Name: "Jennifer Thompson",
    Age: 29,
    Occupation: "Software Developer",
    "Father's ID": 15,
  },
  {
    ID: 7,
    Name: "Christopher Martinez",
    Age: 37,
    Occupation: "Accountant",
    "Father's ID": null,
  },
  {
    ID: 8,
    Name: "Amanda Anderson",
    Age: 45,
    Occupation: "Nurse",
    "Father's ID": 3,
  },
  {
    ID: 9,
    Name: "Joshua Taylor",
    Age: 31,
    Occupation: "Writer",
    "Father's ID": 16,
  },
  {
    ID: 10,
    Name: "Stephanie Clark",
    Age: 27,
    Occupation: "Marketing Manager",
    "Father's ID": null,
  },
  {
    ID: 11,
    Name: "Matthew Rodriguez",
    Age: 39,
    Occupation: "Research Scientist",
    "Father's ID": 6,
  },
  {
    ID: 12,
    Name: "Samantha Lewis",
    Age: 33,
    Occupation: "Graphic Designer",
    "Father's ID": 13,
  },
  {
    ID: 13,
    Name: "Andrew Lee",
    Age: 26,
    Occupation: "Data Analyst",
    "Father's ID": 7,
  },
  {
    ID: 14,
    Name: "Lauren Hall",
    Age: 34,
    Occupation: "Financial Analyst",
    "Father's ID": null,
  },
  {
    ID: 15,
    Name: "Brandon Wright",
    Age: 43,
    Occupation: "Professor",
    "Father's ID": 12,
  },
  {
    ID: 16,
    Name: "Elizabeth Moore",
    Age: 30,
    Occupation: "Pharmacist",
    "Father's ID": 11,
  },
  {
    ID: 17,
    Name: "Joseph Hill",
    Age: 36,
    Occupation: "Police Officer",
    "Father's ID": 6,
  },
  {
    ID: 18,
    Name: "Ashley Baker",
    Age: 24,
    Occupation: "Student",
    "Father's ID": 3,
  },
  {
    ID: 19,
    Name: "Daniel Green",
    Age: 40,
    Occupation: "Entrepreneur",
    "Father's ID": 4,
  },
  {
    ID: 20,
    Name: "Victoria Carter",
    Age: 31,
    Occupation: "HR Manager",
    "Father's ID": 15,
  },
  {
    ID: 21,
    Name: "Robert Adams",
    Age: 38,
    Occupation: "Consultant",
    "Father's ID": 7,
  },
  {
    ID: 22,
    Name: "Natalie Allen",
    Age: 29,
    Occupation: "Social Worker",
    "Father's ID": 12,
  },
  {
    ID: 23,
    Name: "James Young",
    Age: 47,
    Occupation: "Real Estate Agent",
    "Father's ID": 5,
  },
  {
    ID: 24,
    Name: "Olivia King",
    Age: 35,
    Occupation: "Journalist",
    "Father's ID": 10,
  },
  {
    ID: 25,
    Name: "Thomas Scott",
    Age: 26,
    Occupation: "Web Designer",
    "Father's ID": 2,
  },
  {
    ID: 26,
    Name: "Grace Hall",
    Age: 42,
    Occupation: "Project Manager",
    "Father's ID": 16,
  },
  {
    ID: 27,
    Name: "William Campbell",
    Age: 28,
    Occupation: "Photographer",
    "Father's ID": 9,
  },
  {
    ID: 28,
    Name: "Emily Reed",
    Age: 33,
    Occupation: "Event Planner",
    "Father's ID": 1,
  },
  {
    ID: 29,
    Name: "Alexander Phillips",
    Age: 30,
    Occupation: "Software Engineer",
    "Father's ID": 8,
  },
  {
    ID: 30,
    Name: "Sophia Torres",
    Age: 39,
    Occupation: "Artist",
    "Father's ID": 13,
  },
];

export default data;
